spring.application.name=ejercicio10
spring.datasource.url=jdbc:postgresql://dpg-d7r8ahl7vvec73e5k4sg-a.oregon-postgres.render.com/bd_prog4_fernandez
spring.datasource.username=bd_prog4_fernandez_user
spring.datasource.password=OeZfCO0aouJEE3emUcprLN0IPaVICviO

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
